services:
  # PHP Application
  php-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: hello-world-php
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_NAME=${DB_NAME:-hello_world}
      - DB_USER=${DB_USER:-app_user}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./app:/var/www/html
      - php_logs:/var/log
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-f", "/var/www/html/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: hello-world-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./app:/var/www/html:ro
      - nginx_logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      php-app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hello-world-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-hello_world}
      - MYSQL_USER=${DB_USER:-app_user}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Database Administration (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hello-world-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

# Networks
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes
volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local
  nginx_logs:
    driver: local
  php_logs:
    driver: local